# Puerto de la aplicacion
server.port=${PORT:8080}
spring.application.name=portfolio

# Configuracion de Base de Datos
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Pool de conexiones Hikari
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=20000

spring.sql.init.mode=always

# Configuracion de archivos y subidas
file.upload.dir=src/main/resources/static/img/projects
spring.web.resources.static-locations=classpath:/static/,file:src/main/resources/static/

# Optimizacion Java 21 (Virtual Threads)
spring.threads.virtual.enabled=true

# Configuracion de Swagger UI
# Ordenar secciones por nombre (respetara los numeros 1, 2, 3...)
springdoc.swagger-ui.tags-sorter=alpha
# Ordenar metodos (GET, POST, PUT, DELETE)
springdoc.swagger-ui.operations-sorter=alpha